### ISSUE TITLE
LinkedList Module be useful?

### ISSUE THREAD

**Issue by hwayne** [tlaplus/CommunityModules#14]
One of the lessons in _Practical TLA+_ is making a linked list data structure. The entire module is online here: https://github.com/hwayne/practical-tla-plus/blob/master/Chapter%208/LinkedLists.tla

Happy to clean it up in anyway needed, just wanted to check if people think this would actually be useful to include. I don't know how specialized we want to go with these modules.

**Comment by lemmy** [comment]
Closing because the community didn't show interest.
