### ISSUE TITLE
Suppress warning about unmet Json dependency to when a spec uses the operators

### ISSUE THREAD

**Issue by lemmy** [tlaplus/CommunityModules#15]
The warning - introduced by commit b6e67a25e2c023675b745187bd4f4c45f51b8375 - should only be raised when a spec actually extends/instantiates the `Json` module.  The majority of specs, however, won't extend or instantiate the `Json` module.

**Comment by lemmy** [comment]
Workaround: To silence the warning, compile the following `Json.java` and drop the resulting `Json.class` to some location that comes "before" `CommunityModules.jar` on TLC's classpath.


```java
package tlc2.overrides;

public class Json {
	  final static void resolves() {
		  // See TLCOverrides.java
	  }
}
```

**Comment by lemmy** [comment]
The [TLC debugger](https://github.com/lemmy/tlaplus/tree/mku-debugger) might require adding [gson](https://github.com/google/gson) to tla2tools.jar proper.  Porting Json.java to gson would then make the module override without additional dependencies.

**Comment by sadraskol** [comment]
Why not adding jackson deps instead? Are there limitations I'm not aware of?

**Comment by lemmy** [comment]
Please see #29.

**Comment by lemmy** [comment]
#29 done, GSon added to TLC, and `JSon` part of TLC addresses this issue.
