### ISSUE TITLE
Copy useful modules/operators from TLAPS to CommunityModules

### ISSUE THREAD

**Issue by lemmy** [tlaplus/CommunityModules#2]
@muenchnerkindl [suggested](https://github.com/tlaplus/CommunityModules/pull/1#issuecomment-527759652) to copy useful operators from TLAPS:

* Merge [SequencesExt](https://github.com/tlaplus/CommunityModules/blob/master/modules/SequencesExt.tla) and SequenceOps (where do I find SequenceOps?)
* Copy TLAPS to CommunityModules (as workaround to parser errors when users don't have TLAPS installed?!)

**Comment by muenchnerkindl** [comment]
Hi Markus,

SequenceOps is currently in the library/ directory of TLAPS. It doesn't depend on TLAPS, my suggestion is rather to move it (and the Functions module it depends on) to CommunityModules with the understanding that the Toolbox includes that directory in its search path.

Thanks,
Stephan

**Comment by lemmy** [comment]
Hi Stephan,

the CommunityModules are not included in the Toolbox but a dedicated download.  In other words, TLAPS users would have to download the CommunityModules in addition to TLAPS.  What could be done is to include a snapshot of the CommunityModules in the TLAPS distribution, but the modules would generally be out of TLAPS's control.

Best
Markus
