### ISSUE TITLE
ChooseOne operator

### ISSUE THREAD

**Issue by mryndzionek** [tlaplus/CommunityModules#20]
I would like to propose adding `ChooseOne` defined as follows:
```
ChooseOne(S, P(_)) == CHOOSE x \in S : P(x) /\ \A y \in S : P(y) => y = x
```
What would be the best place to put it?

**Comment by muenchnerkindl** [comment]
Perhaps ChooseUnique would be a better name for that operator?

Stephan

**Comment by mryndzionek** [comment]
> Perhaps ChooseUnique would be a better name for that operator? Stephan
> […](#)
> On 15 Oct 2020, at 07:03, mryndzionek ***@***.***> wrote: I would like to propose adding ChooseOne defined as follows: ChooseOne(S, P(_)) == CHOOSE x \in S : P(x) /\ \A y \in S : P(y) => y = x What would be the best place to put it?

Yes, sure, the name is not that important. What is more important is where to put it.

**Comment by mryndzionek** [comment]
I also often end up copying these two operators in my specs:
```
Max(S) == CHOOSE x \in S : \A y \in S : x >= y
Min(S) == CHOOSE x \in S : \A y \in S : x =< y
```
Would be good to also have them in `FiniteSetsExt`.

**Comment by lemmy** [comment]
@mryndzionek Are you going to open PRs for `Max`, `Min`, and `ChooseUnique`?

**Comment by mryndzionek** [comment]
> @mryndzionek Are you going to open PRs for `Max`, `Min`, and `ChooseUnique`?

Yes, I'll have time next weekend. Meanwhile I would also like to add more operators:
```

(***************************************************************************) 
(* If Sets is a set of (non-empty) sets then Choice(Sets) is the set of    *)
(* all choice functions over Sets, that is, functions that associate some  *)
(* with every set in Sets.                                                 *) 
(***************************************************************************) 
Choice(Sets) == { f \in [Sets -> UNION Sets] : \A S \in Sets : f[S] \in S }

(***************************************************************************) 
(* Compute all sets that contain one element from each of the input sets:  *)
(* Shuffle({{1,2}, {3,4}, {5}}) = {{1,3,5}, {1,4,5}, {2,3,5}, {2,4,5}}     *)
(***************************************************************************) 
Shuffle(Sets) == { Range(f) : f \in Choice(Sets) }
```

The author of `Shuffle` and `Choice` is Stephan Merz in [this](https://groups.google.com/g/tlaplus/c/WTb6JZDxorE) email thread (as you probably know :wink: ) Not sure if `FiniteSetsExt` is a good place for `Range` (needed by `Shuffle`).

**Comment by mryndzionek** [comment]
I forgot to add the `ChooseOneUnique` operator in previous PR. It's now in a new one: #23.

**Comment by lemmy** [comment]
Closed https://github.com/tlaplus/CommunityModules/pull/23
