### ISSUE TITLE
The latest version is incompatible with Toolbox < 1.7.1

### ISSUE THREAD

**Issue by josedusol** [tlaplus/CommunityModules#22]
Hello. I guess this is to be expected, but just to confirm, latest CM version fails when loaded on toolbox 1.7.0: 

```
The exception was a java.lang.VerifyError
: class tlc2.overrides.FiniteSetsExt$KSubsetValue overrides final method tlc2.value.impl.SubsetValue.elements()Ltlc2/value/impl/ValueEnumeration;
```

It seems method [SubsetValue.elements()](https://github.com/tlaplus/tlaplus/blob/eb3ff99d167cc3216b4e9f6f822c112aba9597c5/tlatools/org.lamport.tlatools/src/tlc2/value/impl/SubsetValue.java#L696) was declared final before 1.7.1

EDIT: to be more precise, this is from [CM 202009181838](https://github.com/tlaplus/CommunityModules/releases/tag/202009181838) onwards.

**Comment by lemmy** [comment]
Do you want to use operators that were introduced after ...1838 and this is, thus, a blocker for you?

**Comment by josedusol** [comment]
> Do you want to use operators that were introduced after ...1838 and this is, thus, a blocker for you?

No, currently i don't need those operators, now im using 202009162135. 

I'm just saying that i first downloaded latest version, as probably most people will, and get that java exception trying to use any operator. Maybe knowing this "issue" can be useful to somebody, especially if he or she don't understand the message in the exception.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/053926c83553228fd5207e8e3fa8aa3a53f3a17a

**Comment by lemmy** [comment]
Although no general solution to guarantee compatibility, I hope the two commits above address this particular issue for now.

**Comment by lemmy** [comment]
Ouch: https://github.com/tlaplus/tlaplus/commit/36e8182293babf8daffd9eb725d65048b473c340
