### ISSUE TITLE
Configure an github action to run the tests in the Java 1.8 environment

### ISSUE THREAD

**Issue by pfeodrippe** [tlaplus/CommunityModules#32]
We don't test Java 1.8 yet in our CI, see https://github.com/tlaplus/CommunityModules/pull/30#pullrequestreview-563241024 for context.

This should be done after https://github.com/tlaplus/CommunityModules/issues/31 and https://github.com/tlaplus/CommunityModules/issues/34 are resolved.

**Comment by lemmy** [comment]
Blocked by https://github.com/tlaplus/CommunityModules/issues/34#issuecomment-756571840

**Comment by lemmy** [comment]
Obsolete
