### ISSUE TITLE
Add `Reduce` operator to `Functions`

### ISSUE THREAD

**Issue by lemmy** [tlaplus/CommunityModules#35]
```tla
Reduce(op(_,_), fun, from, to, base) == 
  (**************************************************************************)
  (* Reduce the elements in the range from..to of the function's co-domain. *)
  (**************************************************************************)
  LET reduced[i \in from..to] ==
          IF i = from THEN op(base, fun[i])
          ELSE op(reduced[i - 1], fun[i])
  IN reduced[to]
```

/cc @muenchnerkindl @konnov @quicquid

**Comment by quicquid** [comment]
We had a discussion that the current Reduce operator from FiniteSetsEx is a bit restrictive: it works only on functions with integer domain but it also works on sets. On the other hand, it is sometimes needed not to reduce on the full domain, as @lemmy's example from the ewd998 formalization shows. I have added the operators to [a branch in my fork](https://github.com/quicquid/CommunityModules/blob/wip-recursion-operators/modules/FiniteSetsExt.tla) of the community modules. What do you think?

**Comment by lemmy** [comment]
As mentioned in today's call, I suggest moving the functions-related operators out of `FiniteSetsExt` to `Functions.tla` or moving all fold operators to a new module.  I - as a user - wouldn't have looked for functions-related fold operators in `FiniteSetsExt`.  If it is decided to split the operators across `FiniteSetsExt` and `Functions.tla`, comments could point users to the other variants.

Speaking of comments, the format that is the best support by tools, i.e., IDE is:

```tla
OpDecl(params) ==
   (************)
   (* comments *)
   (* comments *)
   (* comments *)
   (************)
   TheOperatorDefinition
```


I'd also suggest adding an example invocation in the comment as in:
https://github.com/tlaplus/CommunityModules/blob/4337afb74653cedcc2a24107759bf1613812db34/modules/FiniteSetsExt.tla#L71-L75

Lastly, there is a precedence of operator aliasing: https://github.com/tlaplus/CommunityModules/blob/4337afb74653cedcc2a24107759bf1613812db34/modules/SequencesExt.tla#L34-L46

PS: TLC takes 2-3 minutes on a laptop to check EWD998 for N=3 and the given state constraint: https://github.com/tlaplus/Examples/blob/master/specifications/ewd998/EWD998.cfg

**Comment by lemmy** [comment]
`Restrict` operator mentioned by @muenchnerkindl :

https://github.com/tlaplus/CommunityModules/blob/4337afb74653cedcc2a24107759bf1613812db34/modules/Functions.tla#L10-L13

**Comment by muenchnerkindl** [comment]
In fact, FoldMap and friends do not use any operator defined in either Functions or FiniteSets, so I believe it would be best to place them in a separate module. Also, please remove the comment in the definition of FoldSet that refers to the operator ReduceSet that will disappear. For the rest, I agree with @lemmy's comments. And I don't know if "FoldMap" is a good name?

**Comment by lemmy** [comment]
WRT the functions/sequence-based folds, what about non-associative operators (fold left vs. right)?  Do we want to open that box of worms?

**Comment by konnov** [comment]
> In fact, FoldMap and friends do not use any operator defined in either Functions or FiniteSets, so I believe it would be best to place them in a separate module.

I also think that we could place all fold-like operators in a separate module, like `Fold.tla` or even `Recursion.tla`. Perhaps, we will discover other forms of recursive operators that are useful in the context of TLA+.

**Comment by lemmy** [comment]
Given that we have `Functions`, `Sequences`, `FiniteSets`, ..., I'd suggest making it `Folds.tla` (with an "s" at the end).

**Comment by konnov** [comment]
>  And I don't know if "FoldMap" is a good name?

True. Would `MapThenFoldSet` work better? It essentially does a map and then fold.

**Comment by quicquid** [comment]
I have created one Folds module for the complicated MapThenFoldSet definition that probably shouldn't be used directly (see comment there) and put the changes into a [pull request draft](https://github.com/tlaplus/CommunityModules/pull/38) that it's easier to compare. I don't think it's ready yet - the least I'm missing is test cases.

I'm wondering two things:
1) Would we also like folds on Graphs? Should we alias FoldSequence in FoldFunction?
2) As @muenchnerkindl said foldLeft / foldRight, we would need an ordering on the set - I could add an ordering to MapThenFoldSet such that we could implement it easily for sequences. Would we want that?

**Comment by lemmy** [comment]
https://github.com/tlaplus/CommunityModules/pull/38 and 0b5fcd46b947e86a5e8fd92748647a7aad4c02dc address this issue.
