### ISSUE TITLE
Add `IOUtils!IOEnv` that equals a record of all environment variables

### ISSUE THREAD

**Issue by lemmy** [tlaplus/CommunityModules#36]
Use cases

* Check spec for various constant values without generating model files

```tla
---- MODULE S ----
CONSTANT N
...
====

---- MODULE MC ----
EXTENDS IOUtils
NEnv == IOEnv.nSetAsEnvVarFromSomeScript
\* If "type" conversion to Integer is desired: CHOOSE n \in 1..10: ToString(n) = NEnv
...
====

---- CONFIG MC ----
CONSTANT 
N = NEnv
...
====
```

* [Initialize TLCSet "register" for each behavior generated as part of the simulation](#simulation)

```shell
export T=42 && tla2tools.jar -simulate num=$T SomeSpec
```

```tla
---- MODULE SomeSpec ----
EXTENDS IOUtils
...
ASSUME \A i \in 1..IOEnv.T: TLCSet(i, 0)
...
Next == 
  \* Record some stats
  TLCSet(TLCGet("diameter"), TLCGet("diameter") + 1)

PostCondition ==
  \A i \in 1..IOEnv.T: TLCGet(i)
====
```

----

Alternative, although Apalache (@konnov) could probably "implement" `IOEnv`:

```tla
TLCGet("env")
```

----

Workaround (Linux/macOS):

```tla
IOExec(<<"printenv", "PATH">>)
```

For some reason, the following equals the empty string although `PATH` is set:

```tla
IOExec(<<"echo", "$PATH">>)
IOExec(<<"/bin/bash", "-c", "echo", "$PATH">>)
```

**Comment by konnov** [comment]
I am not sure I understand the direction, in which this is going. Why would you make TLA+ specifications OS-specific?

**Comment by lemmy** [comment]
@konnov Fair enough, I've made the use-cases above more concrete.
