### ISSUE TITLE
Create Rationals module

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/CommunityModules#4]
This would enable division plus floor/ceiling functions, with the following benefits:
- Calculate the size of the majority of a set (currently passed in as a constant in the Paxos spec)
- Enable specification of algorithms requiring calculating midpoint of array (binary search, sorting, etc.)

Would theoretically include Java module override with an exact-representation Rationals implementation.

**Comment by lemmy** [comment]
Related rescale operator and its TLC module override in https://gist.github.com/lemmy/1eaf4bec8910b25e206d070b0bc80754

**Comment by xxyzzn** [comment]
A Rationals module that TLC can handle might be useful, but isn’t needed for the applications Andrew mentions.  Programs generally implement them using only integer arithmetic with operators that are defined in the Integers module.

I wonder if implementing rationals is really any easier than implementing reals.  Does the set of rationals being only countably infinite make it easier?

Leslie

**Comment by ahelwer** [comment]
Adding integer division to the Integers standard module would work well, correct. Implementing rationals might be a better fit than implementing reals because things like equality checking actually work if you're using something like a pair <<int, uint>> (reduced with GCD after each operation) to represent it internally.

**Comment by xxyzzn** [comment]
Integer division is already in the module—probably defined in the Naturals module that is imported by the Integers module.  (It’s written \div.)

It is impossible to directly write an irrational number in TLA+.  TLC would not be able to evaluate

  CHOOSE x \in Real : x^2 = 2

But neither could it evaluate

  CHOOSE x \in Rational : x^2 = ¼

Leslie

**Comment by ahelwer** [comment]
Hmmm... it would be possible (although grossly inefficient) to implement CHOOSE x \in Rational : x^2 = 1/4 with the standard zig-zag enumeration of the Rationals, right? Although you can't easily restrict the rationals to a finite set like you can with the integers so this might be handing people a footgun. Or maybe TLC doesn't support lazy evaluation of infinite sets. Still, there are many ways to create unbounded monotonically-increasing behaviour with TLA+; why not add another!

Regardless, I think people do expect there are things you can write in TLA+ which work in TLC, and things you can't. I actually appreciate this approach over the "everything you can write can be model checked" strategy taken by other languages, which invariably restricts you from doing things the language designers never considered. Thus I personally would find it acceptable to only implement basic arithmetic & equality operators with the rationals.

But anyway this whole Rationals thing might be a solution in search of a problem, since the only applications I can think of are already solved by integer division. I'll keep a look out for places where I wished I had a rational type as I write more specs.

**Comment by xxyzzn** [comment]
My point is not that TLC should not handle rationals.  It’s that if it’s going to handle rationals, there’s no reason not to have it handle all reals.  There are lots of applications for reals—in particular, real-time and hybrid algorithms.  Currently, they can be handled only with discrete time measured in an integral number of clock ticks.  That’s probably good enough, since it’s unlikely that a system has a bug that’s not discovered in a model with a clock measuring femtoseconds.  But as far as I know, no one has ever tried.

**Comment by lemmy** [comment]
Related: ["Model-checking embedded systems with probabilistic nondeterminism"](https://stevetarzia.com/papers/Tarzia_495_paper.pdf)

**Comment by lemmy** [comment]
[Dyadic Rationals](https://en.wikipedia.org/wiki/Dyadic_rational): https://github.com/tlaplus/Examples/blob/f1c5e358c66b93e6c9ef83f7dc5ddea8921c8159/specifications/Huang/Huang.tla#L128-L177
