### ISSUE TITLE
How to write my operator which can be used in TLA+

### ISSUE THREAD

**Issue by Tsunaou** [tlaplus/CommunityModules#42]
In my work, I want to enumerate all possible event structure satisfying partial order.
However, if we write TLA+ like this:
```TLA+
PartialOrderSubset(s) ==
    LET rels == SUBSET (s \X s)
    IN {po \in rels : IsStrictPartialOrder(po, s)}
```
We should enumerate  all subsets, it's time costing. So I'd like to define my operator by Java and override it. I forked this repository and writes my implementation. See [Update PartialOrderExt](https://github.com/Tsunaou/CommunityModules/commit/5494e0b265b3c1f87b8ca3be6c34444697f5c413)

And then, I built my CommunityModules-deps.jar and added it to TLC's or the Toolbox's TLA+ library path.
I think it will call my implementation in [PartialOrderSubset.java](https://github.com/Tsunaou/CommunityModules/blob/master/modules/tlc2/overrides/PartialOrderExt.java) instead of the original definition in [PartialOrderSubset.tla](https://github.com/Tsunaou/CommunityModules/blob/master/modules/PartialOrderExt.tla) but it didn't work. Is there anything wrong of my settings?

**Comment by lemmy** [comment]
You have to load `PartialOrderExt.java` in `TLCOverrides.java`:

https://github.com/tlaplus/CommunityModules/blob/fa811ceba9c1170003f0dc8fd168b7d7fcfff9bd/modules/tlc2/overrides/TLCOverrides.java#L38-L47
