### ISSUE TITLE
Teach Json module to convert a richer set of TLA+ values

### ISSUE THREAD

**Issue by lvanengelen** [tlaplus/CommunityModules#5]
After specifying a TLA+ spec I would like to export traces of behaviors so I can use them as input for generating tests of the implementation.

Let's say I have the following spec of my system:
```
---- MODULE Box ----
CONSTANTS ItemIds
VARIABLE items

BoxInit == items \in SUBSET ItemIds

Add(i) == items' = items \union {i}
Remove(i) == items' = items \ {i}

BoxNext == \/ \E i \in ItemIds \ items: Add(i)
           \/ \E i \in items: Remove(i)
           \/ UNCHANGED items
====
```

And the following utility spec:
```
---- MODULE BoxTrace ----
EXTENDS Box, Sequences, Json

CONSTANTS ItemIds
VARIABLE trace, json

BoxTraceInit == /\ BoxInit
                /\ trace = [init |-> items, steps |-> <<>>, state |-> items]
                /\ json = ToJsonObject(trace)

BoxTraceNext == \/ \E i \in ItemIds \ items: 
                  /\ Add(i)
                  /\ trace' = [trace EXCEPT !.steps = Append(@, [action |-> "Add", item |-> i]),
                                            !.state = items']
                  /\ json' = ToJsonObject(trace')
                \/ \E i \in items:
                  /\ Remove(i)
                  /\ trace' = [trace EXCEPT !.steps = Append(@, [action |-> "Remove", item |-> i]),
                                            !.state = items']
                  /\ json' = ToJsonObject(trace')

====
```

Running this in simulation mode with `-simulate num=10,file=traces/trace -depth 5 BoxTrace` generates trace files for different behaviors. The last state output in any of those then gives me an initial state, the actions that have been applied together with the parameters and the final state. E.g:
```
STATE_5 == 
/\ items = {i1, i2, i3}
/\ json = "{\"init\": [\"i1\"], \"steps\": [{\"action\": \"Add\", \"item\": \"i3\"}, {\"action\": \"Add\", \"item\": \"i2\"}, {\"action\": \"Remove\", \"item\": \"i3\"}, {\"action\": \"Add\", \"item\": \"i3\"}], \"state\": [\"i1\", \"i2\", \"i3\"]}"
/\ trace = [ init |-> {i1},
  steps |->
      << [action |-> "Add", item |-> i3],
         [action |-> "Add", item |-> i2],
         [action |-> "Remove", item |-> i3],
         [action |-> "Add", item |-> i3] >>,
  state |-> {i1, i2, i3} ]
```

This can then be used to generate a test case by taking the start state, run the steps and comparing the end result with the end state, basically using TLC to generate input for property based testing.

Now the problem is that the above `ToJsonObject` call does not work because

- it only supports a small subset of TLA+ values.
- it does not support any nested structures
- it only supports integer keys and string values

I could just build a sequence of strings and use `ToJsonObject` on it, but being able to use arbitrary structures would be nice.

Also being able to export traces to other programs might have other interesting use cases.

**Comment by lvanengelen** [comment]
For now I created my own quick and dirty implementation tailored to my specific use case, so I can move forward for now. If someone knows about an alternative way of achieving the same, please let me know.

**Comment by lemmy** [comment]
What programming language do you target?  Since TLC is implemented in Java, it would be easy to come up with something more convenient.  Also, simulation will potentially create many redundant traces.  Alternatively, you could use regular model checking with TLC's ```-continue``` parameter and an artificial invariant that is violated after long enough prefixes of behaviors: ```[]TLCGet('level)' < 30```.

By the way, https://github.com/konnov/apalache/issues/77#issuecomment-583594240 seems related.

**Comment by lvanengelen** [comment]
Not a regular programming language :) Trying to give a bit of context: I want to test the behavior of something akin to a visual data flow language. To that end the generated behaviors are actually actions in that data flow language and the states the generated begin and end states. The JSON output will be used to generate a flow in that language through an API together with setup of start state and verification of the end state.

How would TLC being implemented in Java make it more convenient?

The scenarios that we want to test probably won't involve very long traces. Therefore I am not really afraid of redundant traces. I assume I can always use some predicate to avoid uninteresting flows.

One of the benefits of using the simulation mode is that I end up with a single file per behavior. If I use regular model checking I have to figure out where each behavior starts?

**Comment by lemmy** [comment]
* There are ways to call Java code directly from within TLC
* Simulation has no coverage guarantees 
* TLC ```-continue``` prints one behavior after the next (easy to figure out where it starts)

**Comment by lvanengelen** [comment]
- I know about overriding an operator in Java, are there other ways? The API I have to target is implemented in JavaScript so it seems easiest to use JSON as an intermediate format but I can always use more inspiration :-)
- True and avoiding redundant traces up front would be nice I guess :)
- Good to know! But how would I avoid my states from exploding because now the trace itself is part of the state?

**Comment by lemmy** [comment]
With continue the trace doesn't become part of the spec.  You just have TLC print a trace that violates the artificial invariant above and continue causes it to keep looking for more violations (which are then also printed to stdout).

**Comment by lvanengelen** [comment]
I don't seem to get it to work (using the above example with 3 ItemIds). I added `PROPERTY BoxTraceProp` to `BoxTrace.cfg` and `BoxTraceProp == [](TLCGet("level") < 5)` but I don't get any errors. Adding a `Print` to `BoxTraceProp` tells me it is only called when calculating initial states. Any ideas? (I am not really familiar with property testing yet, only had simple invariants for now).

**Comment by lemmy** [comment]
An invariant is an always property. :-) Just define ```TLCGet('level') < 5``` as an invariant.

However, I believe I implemented TLCGet('level') after the last release, which means you have to use the nightly: https://nightly.tlapl.us/dist

**Comment by lemmy** [comment]
Would it be useful in your scenario to invoke the javascript API directly from TLC?  In other words, it shouldn't be too difficult for the current TLA+ trace to launch a (command-line) process with the trace as a parameter.

**Comment by lemmy** [comment]
![Json2](https://user-images.githubusercontent.com/88777/74203567-f4ee1a00-4c24-11ea-82a0-a225ee90f4c0.gif)

**Comment by lvanengelen** [comment]
The last comments will take some time for me to digest :-) It looks interesting but I want to evaluate them wrt. my use case and need to find some time in the coming days to do that.

**Comment by lvanengelen** [comment]
Did some digesting :-)

- got things to work in model checking mode with an invariant checking `TLCGet("level")`. My test model was a bit too simple at first so every reachable state was also an initial state so the `level` would never be higher than 0 :smile: 
- I really like the trick of triggering the output using a disjunction in the invariant! That already makes my custom JSON module approach simpler.
- The generator might be a slow process, so I would probably still go for some intermediate format to separate generating the behaviors from using them as input to the generator. Of course `IOExec` would make it very easy to write some tool to serialize behaviors without having to parse the TLC output. That would be really useful.
- `Trace` would be very nice to have although the same can be had with keeping a trace variable and using `VIEW` to keep it out of the state calculations.

`IOExec` seems very useful in general to integrate TLC with other applications. I probably won't need the full power it brings but it will make things a lot simpler.

**Comment by lemmy** [comment]
If the generator is a slow process, why not detach the forked process in IOExec?  Alternatively, the ```IOSerialize``` operator might be for you.  Note, that @kuujo works on a ```JsonDeserialize``` operator based on which it should be easy to create ```JsonSerialize```.

Sure, you can replace ```Trace``` with a [history variable](https://lamport.azurewebsites.net/pubs/auxiliary.pdf), which might be preferable if one wants to pre-process the TLA+ expressions before they are serialized.  ```Trace``` might be cheaper is some cases though.

**Comment by lvanengelen** [comment]
I actually hadn't noticed `IOExec` and `Trace` were already in the repo, nice! I will try them out. I see that `Trace` is marked experimental. Does that mean it can be removed in some future version?

Is there some early code for `JsonDeserialize` that I could check?

Something unrelated: While downloading the nightly I noticed that there is a signature file there. Which key to use for verification? I could not find any browsing the documents.

**Comment by lvanengelen** [comment]
While trying out your Counter example I ran into some issues:

- As `Trace` outputs a stringified, multiline version of a sequence of states, the argument to Curl gets mangled. For some reason this makes curl error out with an exit code of 6 (can't resolve hostname) on my (Linux) system. If I look closely to the animated GIF you posted, I see that on your system Curl actually returns output but not what is expected. Maybe the difference is in how `ProcessBuilder` interprets the string array on each platform?
- Even if the multiline issue would be solved, as `ToJsonObject` does not handle nested values, it will generate invalid JSON for `Trace` values: `"{\"1\":[x |-> 1],\"2\":[x |-> 2],\"3\":[x |-> 3],\"4\":[x |-> 4],\"5\":[x |-> 5],\"6\":[x |-> 6],\"7\":[x |-> 7],\"8\":[x |-> 8]}"`.

**Comment by lemmy** [comment]
```Trace``` is experimental in that it is - as of now - incompatible with all operators related to randomness.  Additionally, we have to convince ourselves that ```Trace``` is sufficiently useful to maintain it.  Generally, we don't have a defined deprecation/removal policy, because we haven't deprecated/removed operators.

Indeed, ```ToJsonObject``` has to be extended to handle more (e.g. nested) expressions.  Isn't this what this issue is all about?  With a more powerful ```ToJsonObject``` operator, shouldn't the mangling mentioned above no longer be an issue?

**Comment by lemmy** [comment]
Please add a test for ```IOExec``` (similar to https://github.com/tlaplus/CommunityModules/commit/194717b95f143e2144b143488752d1ae3771d577) that reproduces issues with string mangling?

**Comment by lvanengelen** [comment]
Sorry, I got a bit confused and thought you meant the `ToJsonObject` would handle it properly.

I extended my own `ToJson` operator and then it worked after omitting spaces in the output. I think that the splitting in https://github.com/tlaplus/CommunityModules/blob/master/modules/tlc2/overrides/IOUtils.java#L90 is the culprit. I still get some problematic output with escaping for which I have to debug a bit more. Al the backslashes get pretty confusing :-)

I will also come up with a `IOExec` test but it might again take some time before I can continue working on these things.

**Comment by lemmy** [comment]
I see, ```split``` also splits the Json payload.  Would this help: https://stackoverflow.com/a/41700827/6291195 ?

**Comment by lvanengelen** [comment]
Maybe, but it seems a bit hackish to me. Why split at all and not just create the `ProcessBuilder` from the tuple directly (omitting the first argument of `IOExec`)? That would make bulding up the command more awkward though but trying to work around escaping issues always scares me :)

**Comment by lvanengelen** [comment]
I tried to come up with a test for `IOExec` but I would need a command that takes command line arguments and only prints the first one or something similar. I don't know what kind of environment I can assume while running the test. Any suggestions?

**Comment by lemmy** [comment]
The most popular environment for TLC is macOS.  However, the tests (so far) are executed on Linux.  Since both systems have bash, I'd assume bash as the environment.

![Screenshot from 2020-02-25 08-14-33](https://user-images.githubusercontent.com/88777/75266321-0992ec00-57a7-11ea-8246-02e201a1f2c6.png)

**Comment by lvanengelen** [comment]
I did some more debugging. Looking into the behavior of `ProcessBuilder` I found that it does not run the specified commands from within a shell. Therefore `$VARIABLES`, `'quotes'` and other special characters like `~` don't have any effect. Each argument to `ProcessBuilder` is passed as-is to the process so on that level no escaping of quotes or spaces is neccessary.

This has some consequences:
- There should not be any quoting inside the first argument to `IOExec` as this will be directly visible to the program. E.g. the `curl` invocation sends a `'Content-Type:application/json'` (note the single quotes) header which is then not picked up by the remote side.
- Passing a template string as first argument to `IOExec` prohibits calling a program with a space in its path (e.g. `C:/Program Files/some/program.exe`).

I see two possible solutions:
- Let `IOExec` take a single sequence which is then directly passed to `ProcessBuilder` without any space or escape processing. This would allow for spaces in the program path but make invocation a bit more awkward. E.g. `IOExec(<<"curl", "-H", "Content-Type:application/json", "-X", "POST", "-d", ToJsonObject(Trace), "https://postman-echo.com/post")`.
- Let `IOExec` take a template string as first argument and split it on spaces. Then pass the resulting array as argument to`ProcessBuilder` while expanding `%s` inside each array element with the proper element of the passed sequence. Don't perform any space or escape processing on the sequence. This would not allow for spaces in the program path but keep the convenience of the template string:
  ```
  Curl == "curl -H %s -X POST -d %s %s"
  ...
  IOExec(Curl, <<"Content-Type:application/json", ToJsonObject(Trace), "https://postman-echo.com/post">>)
  ```
  Any spaces in arguments to the program inside the template string (e.g. `grep foo bar /some/file`) would be problematic but could be worked around by passing the argument as a parameter instead (`grep %s`).

I came up with two additional tests for `IOExec`: one for quote handling and one for space handling in the argument sequence: https://github.com/lvanengelen/CommunityModules/blob/export/tests/IOUtilsTests.tla

To add a test for spaces in the program path I would need a runnable program in a location with a space in the path.

**Comment by lemmy** [comment]
We could also add ```IOExec``` and ```IOExecTemplate``` to address both scenarios, but simplicity is a good guide.

Assuming git cannot handle directories with whitespaces, can't you create a script in a sub-directory with a whitespace in ```build.xml```?

**Comment by lvanengelen** [comment]
I created two WIP PRs: one for `IOExec` (#7) and one for `Json` (#8). It was a bit unclear to me how to do error handling: the `EvalException` construct is not really clear to me. When to use which error code and what parameters to pass.

I haven't included a test for the 'command with space in path' case yet as I am not that familiar with `build.xml`. I am pretty sure Git handles whitespaces in paths just fine. What would be a proper location to put it in the tree?

**Comment by lvanengelen** [comment]
In #8 I tried to make it possible to handle as much TLC value types as possible. However, I was not able to come up with an instance of each while testing. Probably because some are always evaluated eagerly before being passed to the Java operator? E.g. `OpLambdaValue`, `UndefValue`, `DummyValue`.

**Comment by lvanengelen** [comment]
While using `Trace` I found that it throws on my actual project :( I get an `ArrayIndexOutOfBoundsException`. In `TLCExt.getTrace > traceFile.getTrace > ConcurrentTLCTrace.Record.getPredecessor` the `workers` array is indexed by `state.workerId` which is `32767` while the array size is only`1`.

**Comment by lemmy** [comment]
Can you please share a (minimal) spec that reproduces the bug?

**Comment by lvanengelen** [comment]
I'll try. Hopefully it does not depend too   much on the size of the spec.

Something else, IIUC TLC runs with multiple threads. Is there some way to generate unique names that I could use as a filename parameter to a `IOExec`d command, so invocations won't step on each others toes? Something like the filenames in simulation mode.

Markus Alexander Kuppe <notifications@github.com> schreef op 6 maart 2020 18:43:40 CET:
>Can you please share a (minimal) spec that reproduces the bug?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/tlaplus/CommunityModules/issues/5#issuecomment-595881878

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by lemmy** [comment]
> Something else, IIUC TLC runs with multiple threads. Is there some way to generate unique names that I could use as a filename parameter to a `IOExec`d command, so invocations won't step on each others toes? Something like the filenames in simulation mode.

To clarify, you need to know the thread id that is currently evaluating the next-state relation (init predicate is single threaded)?  Note though that TLC - by default - runs with a single worker.

**Comment by lvanengelen** [comment]
Thread ID or something similar. But for now I can live with a single thread if that's the default. I will first make my spec work :-)

**Comment by lemmy** [comment]
Here's an untested hack where a thread's id would be determined by when it initially evaluates TLC!JavaTime (Randomization standard module would be an alternative/safer source of an id).

```tla
EXTENDS TLC

...

Next == /\ IF TLCGet("level") = 1 THEN TLCSet(42, JavaTime) ELSE TRUE
        /\ PrintT(<<"Thread id:", TLCGet(42)>>)
```

**Comment by lvanengelen** [comment]
I tried to reproduce the `Trace` issue and came up with the following:

```
---- MODULE Counter ----
EXTENDS Integers, TLC, TLCExt

VARIABLE x

Spec == x = 1 /\ [][x < 10 /\ x' = x + 1]_x

Inv == \/ x = 1
       \/ x = 2
       \/ PrintT(<<Trace, x>>)
=====
```

Which outputs:

```
<<<<[x |-> 1]>>, 3>>
<<<<[x |-> 1], [x |-> 2]>>, 4>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3]>>, 5>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3], [x |-> 4]>>, 6>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3], [x |-> 4], [x |-> 5]>>, 7>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3], [x |-> 4], [x |-> 5], [x |-> 6]>>, 8>>
<< << [x |-> 1],
      [x |-> 2],
      [x |-> 3],
      [x |-> 4],
      [x |-> 5],
      [x |-> 6],
      [x |-> 7] >>,
   9 >>
<< << [x |-> 1],
      [x |-> 2],
      [x |-> 3],
      [x |-> 4],
      [x |-> 5],
      [x |-> 6],
      [x |-> 7],
      [x |-> 8] >>,
   10 >>
```
I would expect that `x` in the last element of the trace would always equal `x` but it seems to lag behind. When I remove the `x = 2` an exception is thrown:

```
TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.RuntimeException
: util.Assert$TLCRuntimeException: 
Attempted to apply the operator overridden by the Java method
public static synchronized tlc2.value.impl.Value tlc2.overrides.TLCExt.getTrace() throws java.io.IOException,
but it produced the following error:
Index 77 out of bounds for length 4
```

Where `77` seems to be random.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/c796811b2abe6b5c901b3886118bed3f09251731

**Comment by lemmy** [comment]
If `Trace` should include the success state, the Java override has to be converted from a TLAPlusOperator into an Evaluation that requires a non-arity definition of `Trace`.

**Comment by lvanengelen** [comment]
Sorry, but I don't understand what you mean by `success state`?

Now when I define `Inv == x = 1 \/ PrintT(<<Trace, x>>)`  I get:

```
<<<<[x |-> 1]>>, 2>>
<<<<[x |-> 1]>>, 3>>
<<<<[x |-> 1], [x |-> 2]>>, 4>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3]>>, 5>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3], [x |-> 4]>>, 6>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3], [x |-> 4], [x |-> 5]>>, 7>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3], [x |-> 4], [x |-> 5], [x |-> 6]>>, 8>>
<< << [x |-> 1],
      [x |-> 2],
      [x |-> 3],
      [x |-> 4],
      [x |-> 5],
      [x |-> 6],
      [x |-> 7] >>,
   9 >>
<< << [x |-> 1],
      [x |-> 2],
      [x |-> 3],
      [x |-> 4],
      [x |-> 5],
      [x |-> 6],
      [x |-> 7],
      [x |-> 8] >>,
   10 >>
```

I am surprised by two things:

- the difference between the last element of Trace and the current state `x` being `2`. I would understand a difference of `1`.
- The first line of output having a difference of `1`.

I'm probably missing something about the semantics of `Trace` here.

**Comment by lemmy** [comment]
Are you sure that you downloaded the most recent CommunityModules-XXX.jar and tla2tools.jar?

**Comment by lvanengelen** [comment]
I am not :-\ I had installed the most recent Toolbox but did not rebuild `CommunityModules` now I get the following output with `Inv == PrintT(<<Trace, x>>)` which I think is expected (last part of the trace being the previous state):

```
<<<<>>, 1>>
<<<<[x |-> 1]>>, 2>>
<<<<[x |-> 1], [x |-> 2]>>, 3>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3]>>, 4>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3], [x |-> 4]>>, 5>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3], [x |-> 4], [x |-> 5]>>, 6>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3], [x |-> 4], [x |-> 5], [x |-> 6]>>, 7>>
<< << [x |-> 1],
      [x |-> 2],
      [x |-> 3],
      [x |-> 4],
      [x |-> 5],
      [x |-> 6],
      [x |-> 7] >>,
   8 >>
<< << [x |-> 1],
      [x |-> 2],
      [x |-> 3],
      [x |-> 4],
      [x |-> 5],
      [x |-> 6],
      [x |-> 7],
      [x |-> 8] >>,
   9 >>
<< << [x |-> 1],
      [x |-> 2],
      [x |-> 3],
      [x |-> 4],
      [x |-> 5],
      [x |-> 6],
      [x |-> 7],
      [x |-> 8],
      [x |-> 9] >>,
   10 >>
```

**Comment by lvanengelen** [comment]
I think that's enough for me :-) Export to JSON is working for me now. Thank you for all the help!

**Comment by lemmy** [comment]
https://github.com/tlaplus/CommunityModules/commit/7acb6140bcf08cece2ba0708517fa52146dbd295 convert `Trace` into an `@Evaluation`, which means that it will equals:

```tla
<<<<[x |-> 1]>>, 1>>
<<<<[x |-> 1], [x |-> 2]>>, 2>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3]>>, 3>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3], [x |-> 4]>>, 4>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3], [x |-> 4], [x |-> 5]>>, 5>>
<<<<[x |-> 1], [x |-> 2], [x |-> 3], [x |-> 4], [x |-> 5], [x |-> 6]>>, 6>>
<< << [x |-> 1],
      [x |-> 2],
      [x |-> 3],
      [x |-> 4],
      [x |-> 5],
      [x |-> 6],
      [x |-> 7] >>,
   7 >>
<< << [x |-> 1],
      [x |-> 2],
      [x |-> 3],
      [x |-> 4],
      [x |-> 5],
      [x |-> 6],
      [x |-> 7],
      [x |-> 8] >>,
   8 >>
<< << [x |-> 1],
      [x |-> 2],
      [x |-> 3],
      [x |-> 4],
      [x |-> 5],
      [x |-> 6],
      [x |-> 7],
      [x |-> 8],
      [x |-> 9] >>,
   9 >>
<< << [x |-> 1],
      [x |-> 2],
      [x |-> 3],
      [x |-> 4],
      [x |-> 5],
      [x |-> 6],
      [x |-> 7],
      [x |-> 8],
      [x |-> 9],
      [x |-> 10] >>,
   10 >>
```

**Comment by lvanengelen** [comment]
Nice! Will try it out tomorrow.

**Comment by lemmy** [comment]
Note that it requires the most recent TLC nightly.
