### ISSUE TITLE
FiniteSetsExt!Sum and FiniteSetsExt!Product easily name-clash

### ISSUE THREAD

**Issue by lemmy** [tlaplus/CommunityModules#62]
https://github.com/tlaplus/CommunityModules/blob/23fbb1f4007917fbd07c4b6548d2a8754ac454c4/modules/FiniteSetsExt.tla#L16-L32

`Sum` -> `SumSet`
`Product` -> `ProductSet`

Both names would also be in line with `ReduceSet`.

Objections anybody?

**Comment by muenchnerkindl** [comment]
Sounds good to me.
