### ISSUE TITLE
Add Fold operators for Bags.tla (in new BagsExt.tla)

### ISSUE THREAD

**Issue by lemmy** [tlaplus/CommunityModules#64]
@muenchnerkindl noted that we lack fold operators for the Bags.tla module. @konnov Does Apalache already have folds for bags?

**Comment by konnov** [comment]
> @konnov Does Apalache already have folds for bags?

No, we don't. But I think it should be relatively easy to implement them via `FoldFunction`.

**Comment by lemmy** [comment]
@muenchnerkindl added a TLA+ operator definition of `BagsExt!FoldBag` in https://github.com/tlaplus/CommunityModules/commit/fbe0f276172eeb50853e44ad4970bbb535e72511.  The Java module override for TLC still has to be done.

**Comment by lemmy** [comment]
https://github.com/tlaplus/CommunityModules/pull/66
