### ISSUE TITLE
SequencesExt issue?

### ISSUE THREAD

**Issue by jackmalkovick** [tlaplus/CommunityModules#86]
## Description
I'm was just trying to evaluate some expressions using the Toolbox, with "No Behavior Spec" checkbox on.
I've added CommunityModules.jar and CommunityModules-deps.jar in the "TLA+  Preferences" / "Library Path Locations"

My "spec" is
EXTENDS Sequences, SequencesExt

PS. If I delete SequencesExt from the EXTENDS list, I do not get an error.

## Expected Behavior
No errors

## Actual Behavior
Parsing or semantic analysis failed.

## Your Environment
I'm using the latest tlatoolbox and community modules, downloaded them this morning.
Operating System: Ubuntu

**Comment by lemmy** [comment]
I'm having no issues.  Is there perhaps a name clash with one or more of your operators and the operators defined in `SequencesExt`?

**Comment by jackmalkovick** [comment]
But how name could be a clash if my "spec" is just that one line :)
`EXTENDS Sequences, SequencesExt`

**Comment by jackmalkovick** [comment]
Ah... I found the issue. I also had added to my path the `TLAPS/lips/tlaps` folder. After I've unchecked it works fine.
