### ISSUE TITLE
Add GraphViz module

### ISSUE THREAD

**Issue by Benedicto** [tlaplus/CommunityModules#87]
Today the toolbox support dumping a trace in two pre-defined formats (TLA+ and Json) via the “dumptrace” option: https://github.com/tlaplus/tlaplus/blob/master/general/docs/current-tools.md#command-line-options.

Adding a support for GraphViz's DOT format will be super useful.

It would essentially require writing a GraphViz module that serializes a counterexample defined in TLA+ into GraphViz.

**Comment by lemmy** [comment]
We need a module that defines an operator such as `DotDiGraph` with a graph and two lambdas as parameters and that converts the graph into a string formatted in dot notation.  The input graph will be defined in the usual way, i.e., `[vertices: V, edges: E]` with `V` a set of elements and `E` a set of sequences/tuples, s.t. `e \in E` and `e[1] \in V` and `e[2] \in V`.  The two lambdas format the label of a `v \in V` and `e \in E`, respectively (the labels of an edge `e` can be in its third, fourth, ... component). 


The following resources are related to "dumptrace" specifically:

https://github.com/tlaplus/tlaplus/blob/9e38f31d817a7f53b7120e362999f0ed0244c99c/tlatools/org.lamport.tlatools/src/tla2sany/StandardModules/TLCExt.tla#L50-L64
https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/src/tlc2/value/impl/CounterExample.java

**Comment by Benedicto** [comment]
Thanks lemmy for the pointers. I might take this up since I'm interested in contributing and also get this feature.

**Comment by lemmy** [comment]
A basic GraphViz module has been implemented with https://github.com/tlaplus/CommunityModules/commit/09970155cbbd55737ebec4640f6e0b3185fcbdee and "dumptrace" support in https://github.com/tlaplus/tlaplus/commit/c865dae8012beff6ddee757bb02ec96ef0ea2342.  Please take it from here.

![Untitled](https://user-images.githubusercontent.com/88777/223571718-1ce801c1-1a57-4ec9-8989-dacd9a709e9d.svg)

**Comment by lemmy** [comment]
Add text wrapping:

![Untitled](https://user-images.githubusercontent.com/88777/223898515-4c1824fb-a1cf-4d71-bf6d-eb71faf92b4c.svg)
