### ISSUE TITLE
Repository's README.md is out of date

### ISSUE THREAD

**Issue by jonesmartins** [tlaplus/CommunityModules#91]
The repo's `README.md` lists 15 modules, but the `modules` directory contains 20 `.tla` files (plus `TLCExt.tla` in the `tlaplus` repo, which makes it 21 modules).

Modules in `README.md`:

Bitwise, BagsExt, Combinatorics, DifferentialEquations, FiniteSetsExt, Graphs, IOUtils, Json, Functions, Folds, Relation, SequencesExt, SVG, ShiViz, TLCExt

Missing modules in `README.md`:

CSV, DyadicRationals, GraphViz, HTML, Statistics, VectorClocks

I could write a PR. Maybe even sort modules alphabetically, or separate `...Ext.tla` modules from the others. This would only be cosmetic, though.

For example:

| Module extensions |
| --- |
| [`BagsExt.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/BagsExt.tla)|
| [`SequencesExt.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/SequencesExt.tla) |
| [`TLCExt.tla`](https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/src/tla2sany/StandardModules/TLCExt.tla) |

| Community modules |
| --- |
| [`Bitwise.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/Bitwise.tla) |
| [`CSV.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/CSV.tla)|
| [`Combinatorics.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/Combinatorics.tla)|
| [`DifferentialEquations.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/DifferentialEquations.tla) |   
| [`DyadicRationals.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/DyadicRationals.tla)       |    
| [`FiniteSetsExt.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/FiniteSetsExt.tla)         |    
| [`Folds.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/Folds.tla)                 |       
| [`Functions.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/Functions.tla)             |   
| [`GraphViz.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/GraphViz.tla)              |     
| [`Graphs.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/Graphs.tla)                |   
| [`HTML.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/HTML.tla)                  |  
| [`IOUtils.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/IOUtils.tla)               |   
| [`Json.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/Json.tla)                  |  
| [`Relation.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/Relation.tla)              |   
| [`SVG.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/SVG.tla)                   |   
| [`ShiViz.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/ShiViz.tla)                |   
| [`Statistics.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/Statistics.tla) |
| [`VectorClocks.tla`](https://github.com/tlaplus/CommunityModules/blob/master/modules/VectorClocks.tla) |

**Comment by jonesmartins** [comment]
I'd separate module extensions simply for being extensions, but I see how it's not a big deal after all.
Do you think I should sort all the modules alphabetically, or should I just add the remaining modules to the end?

**Comment by lemmy** [comment]
I wouldn't introduce special terminology for `*Ext` modules.  An alphabetically seems best (I wish markdown tables would be column-sortable).

**Comment by jonesmartins** [comment]
> An alphabetically seems best (I wish markdown tables would be column-sortable).

Yeah... GitLab has JSON tables that are column-sortable. Hopefully GitHub adds this feature soon.

**Comment by lemmy** [comment]
Thanks for your work!

**Comment by jonesmartins** [comment]
It's good to be of service! :-)
