### ISSUE TITLE
Add Functions!Pointwise

### ISSUE THREAD

**Issue by lemmy** [tlaplus/CommunityModules#96]
I propose to add a `Pointwise` operator to [`Functions`](https://github.com/tlaplus/CommunityModules/blob/master/modules/Functions.tla) that applies a (binary) operator `T` to two functions `f` and `g` that share the same domain:

```tla
Pointwise(f, g, T(_,_)) ==
    [ e \in DOMAIN f |-> T(f[e], g[e]) ]
```

We can compose, e.g., addition over functions out of `Naturals!+` and `Pointwise`:

```tla
Plus(f,g) == Pointwise(f,g,+)
```

Obviously, `Pointwise` is not the greatest name.  Suggestions welcome!

**Comment by muenchnerkindl** [comment]
The analogous operator is called `map2` in OCaml. Not sure the name is any better, though.

**Comment by lemmy** [comment]
Damn, naming is hard!  AFAICT `map2` in Ocaml is `zipWith` in Haskell, which collides name-wise with our [`SequencesExt!Zip`](https://github.com/tlaplus/CommunityModules/blob/64513ec1fc4e02bf2b826064a00fa49d97d7eef7/modules/SequencesExt.tla#L344-L360).  Also, `map2` and `zipWith` both operate on lists and not what TLA+ calls functions.

**Comment by lemmy** [comment]
Thanks @muenchnerkindl
